version: '3.7'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=""
            - POSTGRES_PASSWORD=""
            - POSTGRES_DB=""
        ports: 
            - 5432:5432
        logging:
            options:
                max-size: 10m
                max-file: "3"
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=moto@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=bredre
        ports: 
            - "5050:80"