# Generated by Django 4.2.7 on 2023-11-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='membership',
        ),
    ]
