# Generated by Django 4.2.7 on 2023-12-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_profile_photo',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
