# Generated by Django 4.2.7 on 2023-12-12 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_customer_customer_profile_photo_customer_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Street',
            new_name='Streets',
        ),
        migrations.AlterField(
            model_name='customer_profile_photo',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.customer'),
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('artisan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artisanportfolio')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
    ]
