# Generated by Django 4.2.7 on 2023-12-12 10:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ratings_created_at_ratings_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='artisan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.artisanportfolio'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
