# Generated by Django 4.2.7 on 2023-11-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.CharField(choices=[('G', 'GUEST'), ('A', 'ARTISAN')], default='G', max_length=1),
        ),
    ]
